spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.security.oauth2.client.registration.google.redirect-uri=https://${BASE_URL}/login/oauth2/code/google


app.cookies.secure=true
app.cookies.same-site=Lax
app.frontend.base-url=https://braidedbeautyco.com

stripe.secret-key=${STRIPE_SECRET_KEY:}

server.forward-headers-strategy=framework

logging.level.com.braided_beauty=INFO
logging.level.org.springframework.transaction=INFO