spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

app.cookies.secure=true

app.cookies.same-site=None

server.forward-headers-strategy=framework

logging.level.com.braided_beauty=INFO
logging.level.org.springframework.transaction=INFO