-- 1) Drop the old autogenerated unique constraint (safe even if it doesn't exist)
ALTER TABLE appointments
  DROP CONSTRAINT IF EXISTS appointments_appointment_time_key;

-- 2) Create a stable, named partial unique index for "active" appointments only
-- Adjust statuses to match what you consider "blocks the schedule".
CREATE UNIQUE INDEX IF NOT EXISTS ux_appointments_time_active
ON appointments (appointment_time)
WHERE appointment_status IN ('PENDING_CONFIRMATION', 'CONFIRMED', 'COMPLETED');